/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MangaSwing;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import static javax.swing.BorderFactory.createCompoundBorder;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import libmanga.Komikcast;
import libmanga.Manga.Chapter;
import libmanga.Manga.ChapterItem;
import libmanga.Manga.MangaDetail;
import libtool.HTTPConnect;

/**
 *
 * @author naufal
 */
public class ChapterList extends javax.swing.JFrame {

    /**
     * Creates new form ChapterList
     */
    
    private Index index;
    private String link;
    private MangaDetail MD;
    private Chapter chapter;
    
    public ChapterList(Index index, String link) {
        initComponents();
        jTextArea1.setBorder(createCompoundBorder(jTextArea1.getBorder(), BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        this.index = index;
        this.link = link;
        
        Thread t = new Thread(new Runnable(){
            @Override
            public void run() {
                try {
                    setTitle_("Loading ...");
                    jLabel7.setText("Loading ...");
                    jTextField1.setText("Loading ...");
                    jTextField2.setText("Loading ...");
                    try {
                        jLabel1.setIcon(new ImageIcon(ImageIO.read(new File("img/Loading.gif")).getScaledInstance(382, 529, Image.SCALE_SMOOTH)));
                    } catch (IOException ex) {
                        Logger.getLogger(ChapterList.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Thread.sleep(100);
                    Threaded();
                    jLabel7.setText("Done ...");
                } catch (InterruptedException ex) {
                    Logger.getLogger(ChapterList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        });
        
        t.start();
    }
    
    public void setTitle_(String title){
        this.setTitle(title);
    }
    
    public void Threaded(){
        Komikcast KC = new Komikcast();
        MD = KC.getMangaDetail(link);
        this.setTitle(MD.getJudul());
        setup();
    }
    
    public void setup(){
        DefaultTableModel dtm = new DefaultTableModel();
        DefaultListModel dlm = new DefaultListModel();
        dtm.addColumn("");
        dtm.addColumn("");
        
        jTable1.setModel(dtm);
        jList1.setModel(dlm);
        jList1.setCellRenderer(new ChapterListRender());
        
        if(MD.getImg() != null){
            jLabel1.setIcon(new ImageIcon(MD.getImg().getScaledInstance(382, 529, Image.SCALE_SMOOTH)));
        }
        else{
            try {
                jLabel1.setIcon(new ImageIcon(ImageIO.read(new File("img/ErrorImage.png")).getScaledInstance(382, 529, Image.SCALE_SMOOTH)));
            } catch (IOException ex) {
                Logger.getLogger(ChapterList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        jTextField1.setText(MD.getJudul());
        jLabel6.setText("Rating : "+MD.getRating());
        String genre = "";
        for(String s : MD.getGenre()){
            genre += s+",";
        }
        jTextField2.setText(genre);
        
        for(String s : MD.getOther()){
            String [] split = s.split(":");
            if(split.length != 1){
                dtm.addRow(new String[]{split[0], split[1]});
            }
            else{
                dtm.addRow(new String[]{split[0], "?"});
            }
        }
        jTextArea1.setText(MD.getSinopsis());
        jTextArea1.setCaretPosition(0);
        this.chapter = MD.getChapter();
        
        ChapterItem ci [] = this.chapter.getAllChapter();
        for(ChapterItem item : ci){
            dlm.addElement(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thumbnail");

        jLabel2.setText("Judul :");

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");

        jLabel3.setText("Genre :");

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField2");

        jLabel4.setText("Sinopsis");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("List Chapter");

        /*
        */
        jList1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jList1MouseMoved(evt);
            }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane3.setViewportView(jTable1);

        jLabel6.setText("Rating : ");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(17, 17, 17))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        index.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseMoved
        Point p = evt.getPoint();
        jList1.setSelectedIndex(jList1.locationToIndex(p));
        jList1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jList1MouseMoved

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        new ReadChapter(this.chapter, jList1.getSelectedIndex()).setVisible(true);
    }//GEN-LAST:event_jList1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    /*
    private javax.swing.JList<String> jList1;
    */
    private javax.swing.JList<ChapterItem> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
